// <auto-generated />
using Cidades.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Cidades.Data.Migrations
{
    [DbContext(typeof(ApiContext))]
    [Migration("20180805210821_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Cidades.Domain.Entidades.Cidade", b =>
                {
                    b.Property<int>("ibge_id");

                    b.Property<string>("alternative_names");

                    b.Property<bool>("capital");

                    b.Property<decimal>("lat");

                    b.Property<decimal>("lon");

                    b.Property<string>("mesoregion");

                    b.Property<string>("microregion");

                    b.Property<string>("name");

                    b.Property<string>("no_accents");

                    b.Property<string>("uf");

                    b.HasKey("ibge_id");

                    b.ToTable("Cidades");
                });
#pragma warning restore 612, 618
        }
    }
}
